"""Initial schema

Revision ID: 3adc8f74c2ea
Revises:
Create Date: 2026-04-24 02:12:41.147460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3adc8f74c2ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('tenant', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("service_type IN ('factor_service', 'condition_service')", name='check_service_type_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('health_condition', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('improvement_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("factor IN ('Sleep', 'Depression', 'Smoke', 'Stress', 'Movement', 'Nutrition', 'Wellness', 'Obesity')", name='check_factor_valid'),
    sa.CheckConstraint("health_condition IN ('Type 2 Diabetes', 'Cardiovascular Disease', 'Chronic Kidney Disease', 'Cancer', 'Mental Illness', 'Osteoporosis')", name='check_condition_valid'),
    sa.CheckConstraint("severity IN ('Important', 'Very Important')", name='check_severity_valid'),
    sa.CheckConstraint("status IN ('Suffering', 'At Risk')", name='check_status_valid'),
    sa.CheckConstraint("unit IN ('score', 'hours')", name='check_unit_valid'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_records_condition', 'health_records', ['health_condition'], unique=False)
    op.create_index('idx_health_records_date', 'health_records', ['record_date'], unique=False)
    op.create_index('idx_health_records_employee', 'health_records', ['employee_id'], unique=False)
    op.create_index('idx_health_records_factor', 'health_records', ['factor'], unique=False)
    op.create_table('product_conditions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('health_condition', sa.String(length=100), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint("health_condition IN ('Type 2 Diabetes', 'Cardiovascular Disease', 'Chronic Kidney Disease', 'Cancer', 'Mental Illness', 'Osteoporosis')", name='check_product_condition_valid'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'health_condition')
    )
    op.create_index('idx_product_conditions_condition', 'product_conditions', ['health_condition'], unique=False)
    op.create_table('product_factors',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(length=50), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.CheckConstraint("factor IN ('Sleep', 'Depression', 'Smoke', 'Stress', 'Movement', 'Nutrition', 'Wellness', 'Obesity')", name='check_product_factor_valid'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'factor')
    )
    op.create_index('idx_product_factors_factor', 'product_factors', ['factor'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_employee_time', 'recommendations', ['employee_id', 'generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recommendations_employee_time', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_product_factors_factor', table_name='product_factors')
    op.drop_table('product_factors')
    op.drop_index('idx_product_conditions_condition', table_name='product_conditions')
    op.drop_table('product_conditions')
    op.drop_index('idx_health_records_factor', table_name='health_records')
    op.drop_index('idx_health_records_employee', table_name='health_records')
    op.drop_index('idx_health_records_date', table_name='health_records')
    op.drop_index('idx_health_records_condition', table_name='health_records')
    op.drop_table('health_records')
    op.drop_table('products')
    op.drop_table('employees')
    # ### end Alembic commands ###
